# Generated by Django 3.2.25 on 2026-01-11 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_for', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=50)),
                ('project_description', models.TextField()),
                ('personal_note', models.TextField(blank=True)),
                ('hiring_type', models.CharField(choices=[('freelancing', 'Freelancing'), ('company', 'Company')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
