# Generated by Django 2.2 on 2026-01-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20260121_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_draft',
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
