# Generated by Django 2.2 on 2026-01-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20260112_1027'),
        ('notifications', '0002_auto_20260112_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hire_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.HireInquiry'),
        ),
    ]
